const puppeteer = require("puppeteer-core");
const fs = require("fs");
const path = require("path");
const readline = require("readline");

const COOKIES_PATH = path.join(__dirname, "data", "cookies.txt");

// Find Chrome/Edge executable
function findBrowser() {
  const paths = [
    process.env["PROGRAMFILES"] + "\\Google\\Chrome\\Application\\chrome.exe",
    process.env["PROGRAMFILES(X86)"] + "\\Google\\Chrome\\Application\\chrome.exe",
    process.env.LOCALAPPDATA + "\\Google\\Chrome\\Application\\chrome.exe",
    process.env["PROGRAMFILES"] + "\\Microsoft\\Edge\\Application\\msedge.exe",
    process.env["PROGRAMFILES(X86)"] + "\\Microsoft\\Edge\\Application\\msedge.exe",
  ];
  return paths.find((p) => fs.existsSync(p)) || null;
}

async function exportCookies() {
  const browserPath = findBrowser();
  if (!browserPath) {
    console.error("Could not find Chrome or Edge. Please install one.");
    process.exit(1);
  }

  console.log(`\nUsing browser: ${browserPath}`);
  console.log("Opening YouTube login page...\n");

  const browser = await puppeteer.launch({
    executablePath: browserPath,
    headless: false,
    args: ["--no-sandbox"],
  });

  const page = await browser.newPage();
  await page.goto("https://accounts.google.com/ServiceLogin?continue=https://music.youtube.com/");

  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });

  console.log("=========================================");
  console.log("  Log into your YouTube/Google account");
  console.log("  in the browser window that opened.");
  console.log("=========================================");
  console.log("");

  await new Promise((resolve) => {
    rl.question("Press ENTER after you're logged in and see YouTube Music... ", resolve);
  });
  rl.close();

  // Navigate to YouTube to ensure cookies are set
  await page.goto("https://music.youtube.com/", { waitUntil: "networkidle2" });

  const cookies = await page.cookies("https://music.youtube.com");
  await browser.close();

  // Convert to Netscape cookies.txt format
  const lines = [
    "# Netscape HTTP Cookie File",
    "# Generated by SoundBound Link Account",
    "",
  ];

  for (const c of cookies) {
    const domain = c.domain.startsWith(".") ? c.domain : "." + c.domain;
    const flag = "TRUE";
    const securePath = c.path || "/";
    const secure = c.secure ? "TRUE" : "FALSE";
    const expiry = c.expires ? Math.floor(c.expires) : "0";
    lines.push(`${domain}\t${flag}\t${securePath}\t${secure}\t${expiry}\t${c.name}\t${c.value}`);
  }

  fs.writeFileSync(COOKIES_PATH, lines.join("\n"), "utf-8");
  console.log(`\n✅ Cookies saved to: ${COOKIES_PATH}`);
  console.log("✅ YouTube account linked! Restart the server to apply.\n");
}

exportCookies().catch((err) => {
  console.error("Error:", err.message);
  console.log("\nIf puppeteer-core is not installed, run:");
  console.log("  npm install puppeteer-core\n");
  console.log("Alternative: Install 'Get cookies.txt LOCALLY' Chrome extension,");
  console.log("export cookies from youtube.com, and save as:");
  console.log(`  ${COOKIES_PATH}\n`);
});
